import registrationFormModel from "./registrationFromModel";

const {
  formField: {
    prefix,
    firstName,
    lastName,
    email,
    address1,
    address2,
    city,
    state,
    country,
    pincode,
    mobile,
    birthday,
    fromYear,
    toYear,
    streamPuc,
    streamDegree,
    streamPg,
    streamOthers,
    vision,
    profession,
    interest,
  },
} = registrationFormModel;

export default {
  [prefix.name]: "",
  [firstName.name]: "",
  [lastName.name]: "",
  [email.name]: "",
  [address1.name]: "",
  [address2.name]: "",
  [city.name]: "",
  [state.name]: "",
  [country.name]: "",
  [pincode.name]: "",
  [mobile.name]: "",
  [birthday.name]: "",
  [fromYear.name]: "",
  [toYear.name]: "",
  [streamPuc.name]: "",
  [streamDegree.name]: "",
  [streamPg.name]: "",
  [streamOthers.name]: "",
  [vision.name]: "",
  [profession.name]: "",
  [interest.name]: "",
};
